version: "3.7"

volumes:
    db_data:

services:
    postgres:
        image: postgres
        hostname: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: tickets.local
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
              - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

 #   adminer:
 #       image: adminer
 #       hostname: adminer
 #       container_name: adminer
 #       restart: always
 #       ports:
 #           - 8080:8080

    pgadmin:
      image: dpage/pgadmin4
      depends_on:
        - postgres
      ports:
        - "5555:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
      restart: unless-stopped